### ISSUE TITLE
Implement usual arithmetic conversions

### ISSUE THREAD

**Issue by gsomix** [ForNeVeR/Cesium#136]
We need to implement section "6.3.1.8 Usual arithmetic conversions" to support automatic conversions for binary operations (+, -, /, etc).

_- I think we need to finish #135 first and implement also corresponding rules for type propagation in expression. gsomix._

See `TODO[136]` in the code to find the clues for this.

**Comment by impworks** [comment]
Can anyone please explain what the spec means in this line?

> First, if the corresponding real type of either operand is double, the other operand is converted, without change of type domain, to a type whose corresponding real type is double.

Does "without change of type domain" mean we can't expand `int` to `double`?

**Comment by gsomix** [comment]
@impworks I believe it's about distinction between _real_ and _complex_ types, not integer/floating-point.

>6.2.5 Types
> 18 Integer and floating types are collectively called arithmetic types. Each arithmetic type belongs to
one type domain: the real type domain comprises the real types, the complex type domain comprises the
complex types.

**Comment by gsomix** [comment]
@ForNeVeR #135 is merged, so we can remove blocked status.

**Comment by ForNeVeR** [comment]
> @ForNeVeR #135 is merged, so we can remove blocked status.

Thanks, done!
