### ISSUE TITLE
Seems to be we have issue with memory model

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#175]
This code has assumption about how data sitting on the stack.
```
int main(int argc, char *argv[])
{
    int x = 42;
    int a[10];
    return a[-1];
}
```

Cesium compiles, but returns parts of internal .NET structure instead of 42

**Comment by ForNeVeR** [comment]
Technically, this is UB(and I don't think we should even test this behavior), but we should investigate what exactly happens here, anyway.

**Comment by kant2002** [comment]
That's what ILSpy shows
```
public unsafe static int main(int argc, byte** argv)
{
	int num = 42;
	int* ptr = stackalloc int[10];
	return ptr[-1];
}
```

**Comment by ForNeVeR** [comment]
For me, this C# program returned a "right" value of `42`:
```csharp
    int x = 42;
    int* p = stackalloc int[10];
    Console.WriteLine(x);
    Console.WriteLine(p[-8]);
```

A good idea is to check with C#; I didn't thought about that from the beginning for some reason :)

**Comment by ForNeVeR** [comment]
Or even better:
```
    int x = 42;
    int* p = stackalloc int[10];
    Console.WriteLine("x address: " + (long)&x);
    Console.WriteLine("p address: " + (long)p);
    Console.WriteLine("diff: " + ((long)p - (long)&x));
```
```
x address: 617046600076
p address: 617046599920
diff: -156
```

`-156` is very far one from another.

**Comment by ForNeVeR** [comment]
So, I don't believe that relying on the stack layout is a good idea, and UB turns out to be _really_ undefined.

You may proceed with the experiments, but I'm not sure this is a valuable direction of work.
