### ISSUE TITLE
Unicode support in lexer

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#18]
Currently, we use [a lexer we've taken from the Yoakke library](https://github.com/LanguageDev/Yoakke/blob/fcc4b7eb0c5180cbe4bad34b4f0c29d26fafb32f/Sources/Core/Yoakke.C.Syntax/CLexer.cs), which works really well so far.

One downside is that it doesn't support Unicode (probably because the C standard doesn't mandate its support).

I think that Cesium should fully support Unicode, so we should improve our lexer.

See commented-out tests in https://github.com/ForNeVeR/Cesium/pull/17 which were disabled due to this issue.

**Comment by kant2002** [comment]
I think you got it reversed. Unicode supported by Yoakke library, but IMO not as design decision, but as afterthought.

(6.4.2.1) nondigit: one of declare that only core Latin characters are used.  https://github.com/LanguageDev/Yoakke/pull/116
You maybe want that this can be configurable.

**Comment by kant2002** [comment]
So we would be in sync, I use this document http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf

**Comment by ForNeVeR** [comment]
6.4.2.1 allows to use "other implementation-defined character", and I think that Cesium implementation should allow something like `\p{L}` in this list (i.e. any Unicode letters).
