### ISSUE TITLE
Why do we need catch

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#198]
during inspection of code I found following pieces
https://github.com/ForNeVeR/Cesium/blob/7dc3fdbd176d2278e91accc528674294e295ee13/Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs#L46-L51

Do we really need this `catch`, why we cannot make sure that `InvalidOperationException` never happens?

**Comment by ForNeVeR** [comment]
In fact, we don't. I'll remove it, see #198.
