### ISSUE TITLE
Support unions

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#217]
As of now, we only support `struct` declaration and not `union`s, even if those are pretty similar.

Look for the number `217` in the code to find clues to implement this feature.

**Comment by El-Barto3** [comment]
I want to contribute

**Comment by kant2002** [comment]
@El-Barto3 we would be thankful if you implement this.

**Comment by ForNeVeR** [comment]
You could start by [improving the parser](https://github.com/ForNeVeR/Cesium/blob/cabea7fa060c8b299cad6de6de75c6da1e96338a/Cesium.Parser/CParser.cs#L382) and adding a test like [this one](https://github.com/ForNeVeR/Cesium/blob/cabea7fa060c8b299cad6de6de75c6da1e96338a/Cesium.Parser.Tests/ParserTests/DeclarationParserTests.cs#L43-L45).

After that's settled, take a look at the codegen. Once again, I recommend starting from a test and seeing what will break first. The tests for the type codegen [are here](https://github.com/ForNeVeR/Cesium/blob/cabea7fa060c8b299cad6de6de75c6da1e96338a/Cesium.CodeGen.Tests/CodeGenTypeTests.cs#L177-L179).

The entrypoint to start generating a union type is [here](https://github.com:ForNeVeR/Cesium/blob/4371fa9d0c990a16fc05a7632fd1eba22b67e8f0/Cesium.CodeGen/Ir/Declarations/LocalDeclarationInfo.cs#L101-L101). Then, create a new `UnionType` similar to the existing `StructType`, and that's it: you have implemented the `union`!
