### ISSUE TITLE
Subscript expressions (aka index operator) of complex expressions

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#230]
As of now, we don't seem to support something like this:
```c
typedef struct { int[10] x; } foo;
int main() {
  foo a;
  a.x[0] = 0;
}

Look for the number `230` in the code to find clues to implement this feature.

**Comment by te9c** [comment]
Hi! I'd like to contribute but looks like i don't understand the essense of the problem. I use the last build of Cesium and code like this works without expressions.
```c
int main()
{
    int array[6];

    array[1 + 1] = 10;

    return array[1 + 1];
}

```

**Comment by ForNeVeR** [comment]
I may have been wrong in formulating the issue. See this code: https://github.com/ForNeVeR/Cesium/blob/677417723732865ecd848481a5a07eb142cf9461/Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs#L35-L41

Looks like it expects the subscript base (the `a` in `a[10]`) to be simple, and not the index. I'll update the issue description.

**Comment by te9c** [comment]
> As of now, we don't seem to support something like this:
> 
> ```c
> typedef struct { int[10] x; } foo;
> int main() {
>   foo a;
>   a.x[0] = 0;
> }
> 
> Look for the number `230` in the code to find clues to implement this feature.
> ```

```c#
if (_expression is not IdentifierExpression identifier) 
         throw new WipException(230, "Subscription supported only for IdentifierConstantExpression"); 
```
So in that case `_expression` would be `PointerMemberAccessExpression` and we need to get the `_memberIdentifier` of pointer?

**Comment by ForNeVeR** [comment]
Generally, the target expression should just emit something indexable (such as: return an `IValue` or, dunno, something of kind `IIndexableValue`, if we think it's required), and the `SunscrptingExpression` should perform an index operation (say, some address operation). It shouldn't depend on the target expression type.
