### ISSUE TITLE
Better string literal processing

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#235]
Right now, we just strip the double quotes from a literal and then embed it into the binary.

We should process the escape sequences at least.

Look for the number `235` in the code to find clues to implement this feature.

**Comment by kant2002** [comment]
We do not properly parse escape sequences in strings, so `\t`, `\'`, `\"`, `\?`, `\\` etc. More can be found at https://en.cppreference.com/w/c/language/character_constant

**Comment by BaLiKfromUA** [comment]
Hey! I would be happy to solve this issue in the scope of Hactoberfest 2022. Can you assign it to me, and I will send my solution in October?

I don't have much experience with C# (my main langs are Java and Go), but I am very interested in some basics of compiler development.
