### ISSUE TITLE
Unification of emit

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#259]
I was lurking around codebase trying to move something towards #201
What I found is a bit puzzling me why we have 4 different abstractions
```csharp
public interface ITopLevelNode
{
    void EmitTo(TranslationUnitContext context);
}

interface IConstant
{
    void EmitTo(IDeclarationScope scope);
}

internal interface IBlockItem
{
    void EmitTo(IDeclarationScope scope);
}

internal interface IExpression
{
    void EmitTo(IDeclarationScope scope);
}
```

That does not sounds right for me. so what do you guys think about having 
```csharp
class Emitter
{
   public void EmitDefinition(ITopLevelNode node, TranslationUnitContext context);
   public void EmitBlockItem(IBlockItem blockItem, IDeclarationScope scope);
   public void EmitExpression(IExpression expression, IDeclarationScope scope);
}
```
I deliberately remove `EmitConstant` since emitter can know how to emit constant expression, and there no point to have that as separate method. Internally maybe.

Also I do not see a value in the `IConstant` over simple `IExpression`. What special treatment constants require? We have add property `bool IExpression.IsConstExpression` and it would be the same.

Also why we have special `ITopLevelNode` and not just special `IBlockItem` which represent top-level definition. Not sure about that one, but even if this definitions require some additional context, that can be handled by giving `IDeclarationScope` access to `TranslationUnitContext` within which emit happens.

**Comment by ForNeVeR** [comment]
I can't imagine the implementation of such `Emitter`, what would it be? A huge `switch` on types? I'd say this is a step back from the current design.

> Also I do not see a value in the `IConstant` over simple `IExpression`.

Currently, expressions and constants have no relation to each other. Constant is a more low-level item than an expression. You can check usages of this method to see the context.

> Also why we have special `ITopLevelNode` and not just special `IBlockItem` which represent top-level definition.

Because there's technically no _block_ on the top level. Though this one may be improved I think.

**Comment by kant2002** [comment]
> A huge `switch` on types?

Yes. So far, that's only option that I see. I dislike it with a passion too, but

> I'd say this is a step back from the current design.

Consider that right now IR nodes know about Cecil, and process of emitting is spread across whole IR tree which is bad. I expect that a lot of IR nodes will be never emitted, like `if`/`for`/`while`/`switch` and instead of them, other nodes which is smaller in nature to be used as basis for emit.

Also consider how we will have separate processes for IR transformations? I worry a lot that we will mix concepts from different phases if everything would be in single class.

> Constant is a more low-level item than an expression. 

I got your point. Agree. I would say from quick glance, too many stuff knows about how to emit itself. I would like to have IR more of internal representation, and not internal logic.

> Though this one may be improved I think.

By itself it's fine, I probably would like to have `ITopLevelNode` to be renamed to `IDefinition` or something closer to that that. Just name changes IMO helps. But whole changes in that areas, depends on how our discussion would be flowing.

**Comment by kant2002** [comment]
> A huge `switch` on types?

I think by default I think that it would be some method which visit base interfaces within each would be switches. so not that much problematic, but some areas probably would have a larger then usual switch.

**Comment by ForNeVeR** [comment]
> I would say from quick glance, too many stuff knows about how to emit itself

Because this wasn't recognized as a problem when the stuff was designed. And, to be honest, I'm still not sure this _is_ a current problem; though that's possibly because I can't see the limits of the current design well, _yet._

**Comment by kant2002** [comment]
Now I think I have rationale why I want to have Emitter class which represent process of emitting.
Currently we have 2 processes called Lower and Emit and will have more in the future. Logic of these processes spread thin across different classes. So rationalize what’s going on become harder and harder. Common way to have logic for single process within single file is to have construct like this https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/Symbols/SymbolVisitor.cs

Whether we use exact pattern or not for emit this is subject to discussion, but right now I have more incentive push for combining logic of single process into single class

**Comment by ForNeVeR** [comment]
Now I think I can see the limitations of the current design. It doesn't really allow to do any cross-node optimizations or processing; if the IR node knows everything for the operation (say, lowering or an optimization), then all is good. But if it isn't, then it's really unclear what to do.

So, okay, we may try start extracting some parts of the code into a set of classes designed for batch node processing. And even (sigh) start adding some visitors.
