### ISSUE TITLE
Implementing stdbool.h

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#292]
I believe implementing this header would be good first issue. Just read 7.18 on page 211 and implement what's there

**Comment by reima** [comment]
I would like to work on this.

This looks like a cool project 🙂 I'm proficient in both C# and C, and dabble in compiler construction on the side, so I think this fits my profile.

**Comment by kant2002** [comment]
It’s yours. That’s perfect issue to get yourself familiar with a project
