### ISSUE TITLE
Static function support

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#344]
Cesium should support static functions at the top level (file scope). E.g.
```c
static void foo(void) { }
```

This should be compiled as a static method in the translation unit class.

Look for number `344` in the sources when implementing this feature.

**Comment by abrahamFerga** [comment]
Looks like this issue was fixed already in the commit `d21162b6bf82a3f7480c3cc81230ed252b5a1dbd`.
This case is being compiled correctly.
