### ISSUE TITLE
If output file has no extension compiler crashes

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#38]
```
dotnet run --project Cesium.Compiler -- Cesium.IntegrationTests/arithmetics.c out
Cesium v0.0.0.0
Processing input file Cesium.IntegrationTests/arithmetics.c.
Unhandled exception. System.Exception: Unknown file extension: .
```

**Comment by ForNeVeR** [comment]
Currently, it detects the module kind from the file extension (which is mostly useful for .NET Framework, but still). Why would you like to create an extension-less file, and which should be its kind?

I guess, we could add a parameter to specify the module kind explicitly.

**Comment by kant2002** [comment]
This is Linux. I did not expect extensions there that much. That could be good first issue

**Comment by ForNeVeR** [comment]
I understand this is Linux, but what kind of module would that mean? Normally, .NET programs have extensions, and on Linux, they aren't (usually) runnable as native binaries. If we aren't going to talk about apphost binaries (which we'll probably eventually support in Cesium SDK, but at a much later point of time).

**Comment by kant2002** [comment]
I would say that intuitively this is Exe file (managed). But at least compiler should not crash.

**Comment by ForNeVeR** [comment]
It would be very odd for me to see a managed executable file without an `.exe` extension.

Though I'm okay with adding an option to specify the module kind, if even for completeness only.
