### ISSUE TITLE
Local struct declaration can't be resolved

### ISSUE THREAD

**Issue by abrahamFerga** [ForNeVeR/Cesium#453]
Local struct declaration can't be resolved:
```
int main() {
    struct bar {
        int x;
        int y;
    };
    struct bar foo;
    foo.x = 10;
    return foo.x;
}
```

It works if the struct is declared globally.
Found this behavior while working in #450, it makes the following case fail:

```
int main() {
    struct bar {
        int x;
    };
    return sizeof(struct bar);
}
```

**Comment by abrahamFerga** [comment]
Hello everyone, 

I could use some guidance regarding a topic in the C standard (6.2.1 Scopes of identifiers):

> `An identifier can denote an object; a function; a tag or a member of a structure, union, or enumeration;
a typedef name; a label name; a macro name; or a macro parameter. The same identifier can denote
different entities at different points in the program.`

My initial idea was to create a list of structures within the `GlobalConstructorScope`, `FunctionScope`, and `BlockScope`, similar to what we're doing for variables.

`private readonly Dictionary<string, VariableInfo> _variables = new();`

However, if we go this route, we might need to do the same for functions, structs, enums, typedefs, and more. What are your thoughts on this? Am I deviating from the main goal of Milestone 61? While it is possible to declare functions, structs, etc., locally, it's not as common, as far as I know.

```
int main() {
    int localFunc()
    {
        return 1;
    }
    return localFunc();
}
```

Cheers.

**Comment by ForNeVeR** [comment]
I think that we should port the same structure we currently have for types in the `TranslationUnitContext`:
```
    private readonly Dictionary<IGeneratedType, TypeReference> _generatedTypes = new();
    private readonly Dictionary<string, IType> _types = new();
    private readonly Dictionary<string, IType> _tags = new();
```

Together with the accompanying methods (perhaps `ResolveType` as well?).

Perhaps let's try to extract it into a separate type, like `TypeDefinitionScope`, and then use it in `TranslationUnitContext` and other contexts that may own the type declarations?

> Am I deviating from the main goal of Milestone 61?

Meh, the milestones are here to somewhat direct the development, and definitely not to stop us from implementing whatever we like to :)

> While it is possible to declare functions, structs, etc., locally, it's not as common, as far as I know.

The most interesting features to implement are often the least common ones :)
