### ISSUE TITLE
`LValueArrayElement::GetValueType` is implemented weirdly

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#477]
Currently, `LValueArrayElement::GetValueType` returns the type of the array itself. I don't think it is a correct implementation: it should actually return the type of the array element, not the array itself.

But we'll also need to figure out how and why it works currently with an incorrect implementation. How's that `GetValueType` used anyway?

**Comment by HiddenNode** [comment]
Trying to resolve this, i seems to me that the class `LValueArrayElement` is never being used, because its associated expression  `SubscriptingExpression` is always lowered into an `IndirectionExpression`.

**Comment by ForNeVeR** [comment]
That would explain why it works at all.

Then let's try to drop it and see if anything breaks 😅
