### ISSUE TITLE
C <-> C# interop

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#57]
Based on questions which was raised in #55 I think it is time to discuss mapping between C types and C# types, which then would be moved to documentation.

## Base types

| C type | C# type |
| -------- | ---------|
| char | ushort |
| signed char | short |
| char * | byte* |
| const char * | byte |
| int | int |
| unsigned | uint |
| unsigned int | uint |
| long | long |
| unsigned long | ulong |
| float | float |
| double | double |
|  long double | double |
| void | void |
| _Bool | bool |

Pointer types in C# would be represented as base type + * except `char *` which is `byte *` because we want UTF-8.

**Comment by ForNeVeR** [comment]
I propose a number of changes to this system.
| C type | C# type |
| -------- | ---------|
| char | ~~ushort~~ byte |
| signed char | ~~short~~ sbyte |
| const char * | ~~byte~~ byte* (this one was just a typo, I think?) |

A couple of important types you forgot:
| C type | C# type |
| -------- | ---------|
| unsigned char | byte |
| long long | long |


Here, by `char`, I assume you really mean `char` type, like `char x;`, and not a character literal like `'a'`, which is a different story in C (`sizeof 'a'` is commonly `4`, as you might know, which is even different between C and C++).
