### ISSUE TITLE
Endless loop compiled with ret in the beginning

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#633]
_Originally posted by @ForNeVeR in https://github.com/ForNeVeR/Cesium/pull/617#discussion_r1740187552_

https://github.com/ForNeVeR/Cesium/blob/f1b5204e9d1f0869ed8c4ee0caf3c3e41ad6a5a9/Cesium.CodeGen.Tests/CodeGenMethodTests.cs#L351-L352

Codegen for this method is quite suspicious:
```
System.Int32 <Module>::test()
  IL_0000: nop
  IL_0001: ret
  IL_0002: nop
  IL_0003: br IL_0000
  IL_0008: nop
```
`ret` seems to be the first executed instruction.

This shouldn't be so.

**Comment by kant2002** [comment]
It's really indicator that we need dead code elimination.
```
System.Int32 <Module>::test()
  IL_0000: nop // Beginning of for

  IL_0001: ret // return 

  IL_0002: nop // end of for
  IL_0003: br IL_0000 // jump to the beginning of for
  IL_0008: nop
```

I think this is not an issue perse. Just ugly codegen. I would like to continue move forward with transformation and produce proper basic blocks, that way we can perform reachability analysis.
