### ISSUE TITLE
.NET SDK

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#80]
I want the users to be able to develop Cesium projects using .NET SDK, with a workflow like this:
1. Create a `.cesproj` file similar to this:
   ```xml
   <Project Sdk="Cesium.Sdk/1.0.0">
     <PropertyGroup>
       <TargetFramework>net6.0</TargetFramework>
     </PropertyGroup>
   </Project>
   ```
2. Run `dotnet build`: it should download the `Cesium.Sdk` from NuGet, set up compiler target, probably even download the standard library from NuGet!

In other words, Cesium projects should be fully compatible with normal .NET ecosystem; ideally, it should even be possible to use `<ProjectRefrence Include="../something.cesproj" />` in a C# project, and get the reference!

Depends on:
- [x] #161

**Comment by kant2002** [comment]
This is how I done F* SDK https://github.com/kant2002/fstarmsbuildsdk . Tools packaging is based on how Zig handle that. I just borrow simplified version of it. Cesium has ability package itself as MSBuild task, so some variations possible.

**Comment by ForNeVeR** [comment]
Wow, yeah, your F* SDK would really help here. I didn't think about it myself.
