### ISSUE TITLE
Linux support is missing

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#9]
Right now application generates EXE file, which I can run under Mono. but I definitely prefer use .NET Core. Anything what can be done?

**Comment by ForNeVeR** [comment]
There are a couple of things, actually.

First of all, current Cesium output actually generated an assembly compatible with all flavors of .NET: it runs by .NET Framework, Mono or .NET Core/.NET 5+.

The main thing that's really missing to be able to run the binary using `dotnet` is the `runtimeconfig.json`.

In the bright future, this file is going to be generated by the SDK (same as with "serious" languages like C#). But for now, I guess we could add a stub runtimeconfig generator.

A second thing is to generate true .NET Core binaries: for now, dotPeek detects our `out.exe` as a .NET Framework executable, which I guess is detected by an `mscorlib` reference. In the future, we'll fix this, too, and allow the user to choose the system assembly to reference.

**Comment by ForNeVeR** [comment]
> A second thing is to generate true .NET Core binaries: for now, dotPeek detects our `out.exe` as a .NET Framework executable, which I guess is detected by an `mscorlib` reference. In the future, we'll fix this, too, and allow the user to choose the system assembly to reference.

This part has been extracted into #10.

**Comment by kant2002** [comment]
Under SDK do you mean MSBuild SDK? or just collection of tools?

**Comment by ForNeVeR** [comment]
I mean an MSBuild SDK (like `<Project Sdk="Cesium/1.0.0">`). Cesium will get one sooner or later.
